---
- name: How to output to the screen with debug
  hosts: localhost
  connection: local
  gather_facts: True

  vars:
    vendorip: '192.168.22.55'

  tasks:
  - name: Print out to the screen
    debug:
      msg: "Welcome to Ansible"

  - name: Print a message variable
    debug:
      msg: "The vendor IP is {{vendorip}}"
      # Note that recall within the msg parameter requires mustache-brackets
  
  - name: Print just a variable
    debug:
      var: vendorip

  - name: Print only with verbosity
    ansible.builtin.debug:     # This is an example of a Fully Qualified
      var: vendorip
      verbosity: 2    # require -vv at runtime for this task to display

  - name: Reveal ansible facts about local host
    debug:
      var: ansible_facts["interfaces"]

