---
- name: Playbook - Install figlet
  hosts: planetexpress:!farnsworth # we want to take the planetexpress group and remove farnsworth
  connection: ssh # default is to use the connection plugin ssh.py
  gather_facts: yes

  tasks:
  - name: using apt to install figlet
    ansible.builtin.apt: # the module we want to run, apt.py
        name: figlet
        state: absent
    become: yes # elevate status to admin, sudo, enable, etc.

