---
- name: Avoiding the use of ansible raw module
  hosts: tx_mid_svr
  connection: ssh
  gather_facts: yes


  tasks:
  - name: Create a file over an SSH channel
    copy:
      content: "{{ ansible_env.LOGNAME }}"
      dest: newfile01.txt
      force: yes    # remote file will be replaced when contents are different than the source

  - name: Create a second file over an SSH channel
    copy:
      content: "Hello world!"
      dest: newfile02.txt
      force: yes
